// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/CreateShop": {
            "post": {
                "description": "สร้างร้านค้าใหม่ลงในฐานข้อมูล",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shop"
                ],
                "summary": "เพิ่มร้านค้า",
                "parameters": [
                    {
                        "description": "ข้อมูลร้านค้า",
                        "name": "Shop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Shop"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Shop"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "ล็อกอินด้วย Username, Email หรือ เบอร์โทรศัพท์",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "เข้าสู่ระบบ (Login)",
                "parameters": [
                    {
                        "description": "ข้อมูลสำหรับ Login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "ลงทะเบียนผู้ใช้ใหม่เข้าสู่ระบบ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "สมัครสมาชิก",
                "parameters": [
                    {
                        "description": "ข้อมูลสำหรับสมัครสมาชิก",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: success",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/createProduct": {
            "post": {
                "description": "สร้างรายการสินค้าใหม่ลงในฐานข้อมูล",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "เพิ่มสินค้า",
                "parameters": [
                    {
                        "description": "ข้อมูลสินค้า",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.LoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "description": "รับค่ามาเป็น \"username\" แต่เราจะเอาไปเช็คว่าเป็น Email หรือ เบอร์โทร ใน Controller",
                    "type": "string"
                }
            }
        },
        "models.Product": {
            "type": "object",
            "required": [
                "category_id",
                "cost_price",
                "img_product",
                "name",
                "sell_price",
                "shop_id",
                "unit"
            ],
            "properties": {
                "barcode": {
                    "description": "[เทคนิค] Barcode ควรเป็น Pointer (*string) เพื่อรองรับค่า NULL",
                    "type": "string",
                    "example": "885123456789"
                },
                "category_id": {
                    "type": "integer",
                    "example": 2
                },
                "cost_price": {
                    "type": "number",
                    "example": 10.5
                },
                "img_product": {
                    "type": "string",
                    "example": "https://image.url/cola.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "น้ำอัดลม โคล่า"
                },
                "product_id": {
                    "type": "integer"
                },
                "sell_price": {
                    "type": "number",
                    "example": 15
                },
                "shop_id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "boolean",
                    "example": true
                },
                "stock": {
                    "description": "gte=0 คือ มากกว่าหรือเท่ากับ 0",
                    "type": "integer",
                    "minimum": 0,
                    "example": 100
                },
                "unit": {
                    "type": "string",
                    "example": "ขวด"
                }
            }
        },
        "models.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "password",
                "phone",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "poder"
                }
            }
        },
        "models.Shop": {
            "type": "object",
            "required": [
                "address",
                "name",
                "phone",
                "pin_code",
                "user_id"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 ถ.สุขุมวิท แขวงคลองเตย เขตคลองเตย กทม 10110"
                },
                "img_qrcode": {
                    "type": "string",
                    "example": "https://image.url/qrcode.jpg"
                },
                "img_shop": {
                    "type": "string",
                    "example": "https://image.url/homeshop.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "จันทร์เพ็ญ"
                },
                "phone": {
                    "type": "string",
                    "example": "0985490445"
                },
                "pin_code": {
                    "type": "string",
                    "example": "191047"
                },
                "shop_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EazyStore API",
	Description:      "API สำหรับระบบ EazyStore",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
